<a href="https://colab.research.google.com/github/inspire2029-sudo/phantoms-ai-week3/blob/main/W3D2_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PHANTOMS | W3D2
## Data Cleaning and Preparation

### Cleaning and Preparing Data for Machine Learning

في التاسك ده هتدرب على استكشاف البيانات وتنظيفها وتجهيزها قبل استخدامها في Machine Learning الـ

هنشتغل على Missing Values والبيانات الرقمية والنصية
وهنحدد الـ Features والـ Label
وكمان هنطبق بعض عمليات Pandas الأساسية

In [27]:
import numpy as np
import pandas as pd

## 1) Loading the Dataset

هنستخدم Titanic Dataset لأنها فيها بيانات رقمية ونصية بالإضافة لـ Missing Values
وده هيساعدنا نتدرب على تنظيف وتجهيز البيانات قبل استخدامها في Machine Learning

In [28]:
import seaborn as sns

df = sns.load_dataset("titanic")

In [29]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## 2) Exploring the Dataset

قبل ما ننظف البيانات لازم نفهم شكلها الأول
هنستخدم info و describe و isnull عشان نعرف أنواع الأعمدة وحجم الـ Missing Values

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [31]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [32]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [33]:
numerical_columns = df.select_dtypes(include=np.number).columns
categorical_columns = df.select_dtypes(exclude=np.number).columns

print("Numerical Columns:")
print(list(numerical_columns))

print("\nCategorical Columns:")
print(list(categorical_columns))

Numerical Columns:
['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']

Categorical Columns:
['sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

## 3) Handling Missing Values

مش كل Missing Values هنتعامل معاها بنفس الطريقة

القرار بيعتمد على نوع البيانات ونسبة القيم الناقصة وأهمية العمود

- age: هنستخدم Median لأن العمود رقمي وفيه عدد كبير من القيم الناقصة والـ Median أكثر مقاومة للقيم المتطرفة
- embarked: هنستخدم Mode لأن العمود Categorical وعدد القيم الناقصة قليل جدًا
- embark_town: هنحذف العمود لأنه يحتوي على نفس معلومات embarked بشكل مكرر
- deck: هنحذف العمود لأن نسبة القيم الناقصة فيه كبيرة جدًا وبالتالي تعويضها هيكون غير موثوق

In [34]:
df["family_size"] = df["sibsp"] + df["parch"] + 1

df[["sibsp", "parch", "family_size"]].head()

   sibsp  parch  family_size
0      1      0            2
1      1      0            2
2      0      0            1
3      1      0            2
4      0      0            1

In [35]:
df["age"] = df["age"].fillna(df["age"].median())

In [36]:
df["age"].isnull().sum()

np.int64(0)

In [37]:
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

In [38]:
df["embarked"].isnull().sum()

np.int64(0)

In [39]:
df = df.drop(columns=["deck", "embark_town", "class", "who", "adult_male", "alive"])

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     891 non-null    object
 8   alone        891 non-null    bool
 9   family_size  891 non-null    int64
dtypes: bool(1), float64(2), int64(5), object(2)
memory usage: 63.6+ KB

In [41]:
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [42]:
df.groupby("pclass")["survived"].mean()

pclass
1    0.629630
2    0.472826
3    0.242363
Name: survived, dtype: float64

In [43]:
features = [
    "pclass",
    "sex",
    "age",
    "sibsp",
    "parch",
    "fare",
    "embarked",
    "alone",
    "family_size"
]

label = "survived"

X = df[features]
y = df[label]

print("Features:")
print(list(X.columns))

print("\nLabel:")
print(y.name)

Features:
['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'alone', 'family_size']

Label:
survived

In [44]:
X = pd.get_dummies(
    X,
    columns=["sex", "embarked"],
    drop_first=True,
    dtype=int
)

X.head()

,pclass,age,sibsp,parch,fare,alone,family_size,sex_male,embarked_Q,embarked_S
0,3,22.0,1,0,7.2500,False,2,1,0,1
1,1,38.0,1,0,71.2833,False,2,0,0,0
2,3,26.0,0,0,7.9250,True,1,0,0,1
3,1,35.0,1,0,53.1000,False,2,0,0,1
4,3,35.0,0,0,8.0500,True,1,1,0,1

In [45]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pclass       891 non-null    int64
 1   age          891 non-null    float64
 2   sibsp        891 non-null    int64
 3   parch        891 non-null    int64
 4   fare         891 non-null    float64
 5   alone        891 non-null    bool
 6   family_size  891 non-null    int64
 7   sex_male     891 non-null    int64
 8   embarked_Q   891 non-null    int64
 9   embarked_S   891 non-null    int64
dtypes: bool(1), float64(2), int64(7)
memory usage: 63.6 KB

In [46]:
cleaned_df = X.copy()
cleaned_df[label] = y

cleaned_df.head()

,pclass,age,sibsp,parch,fare,alone,family_size,sex_male,embarked_Q,embarked_S,survived
0,3,22.0,1,0,7.2500,False,2,1,0,1,0
1,1,38.0,1,0,71.2833,False,2,0,0,0,1
2,3,26.0,0,0,7.9250,True,1,0,0,1,1
3,1,35.0,1,0,53.1000,False,2,0,0,1,1
4,3,35.0,0,0,8.0500,True,1,1,0,1,0

In [47]:
print("Missing Values:")
print(cleaned_df.isnull().sum())

print("\nShape:")
print(cleaned_df.shape)

print("\nData Types:")
print(cleaned_df.dtypes)

Missing Values:
pclass         0
age            0
sibsp          0
parch          0
fare           0
alone          0
family_size    0
sex_male       0
embarked_Q     0
embarked_S     0
survived       0
dtype: int64

Shape:
(891, 11)

Data Types:
pclass           int64
age            float64
sibsp            int64
parch            int64
fare           float64
alone             bool
family_size      int64
sex_male         int64
embarked_Q       int64
embarked_S       int64
survived         int64
dtype: object

In [48]:
cleaned_df.to_csv("cleaned_data.csv", index=False)

In [49]:
import os

print(os.path.exists("cleaned_data.csv"))

True

In [50]:
import os

print(os.listdir())

['.config', 'cleaned_data.csv', 'sample_data']

## 4) Final Result

تم تنظيف وتجهيز البيانات بنجاح

- تم التعامل مع Missing Values
- تم حذف الأعمدة التي تحتوي على نسبة Missing Values مرتفعة أو معلومات مكررة
- تم إنشاء Feature جديدة وهي family_size
- تم تحديد الـ Features والـ Label
- تم تحويل البيانات الـ Categorical إلى بيانات رقمية
- تم التأكد من عدم وجود Missing Values في البيانات النهائية
- تم حفظ البيانات النظيفة في cleaned_data.csv